#!/usr/bin/env python3
"""
sprite2db.py - Design tool (NOT part of the delivered program).
Converts a sprite into an assembler 'db' table for TASM.

Accepts two input formats:

1) PNG image (drawn in Piskel, LibreSprite, Aseprite...):
   - Transparent pixels -> color 0 (transparent in the game).
   - Every other pixel -> the closest color of PALETTE below.
   - Needs Pillow:  python -m pip install pillow

2) Text file (.txt):
   - Lines starting with '#' are comments.
   - 'map X N' lines say which palette index N the character X uses.
   - One line per pixel row, all rows the same width.
   - '.' is always color 0 (transparent).

Usage:
  python sprite2db.py <sprite.png|sprite.txt> <label> <output.inc>
Example (run from C:\\ASM):
  python herramientas\\sprite2db.py sprites\\frasco5.png frasco5 master\\frasco5.inc
"""
import sys

# Palette index -> (R, G, B). These are the 15 default VGA colors.
# When the custom palette (Phase 2) is ready, this table gets the same
# colors programmed through ports 3C8h/3C9h, so both always match.
PALETTE = {
    1: (0, 0, 170),      2: (0, 170, 0),      3: (0, 170, 170),
    4: (170, 0, 0),      5: (170, 0, 170),    6: (170, 85, 0),
    7: (170, 170, 170),  8: (85, 85, 85),     9: (85, 85, 255),
    10: (85, 255, 85),   11: (85, 255, 255),  12: (255, 85, 85),
    13: (255, 85, 255),  14: (255, 255, 85),  15: (255, 255, 255),
}

def closest_index(rgb):
    """Palette index whose color is nearest to rgb (squared distance)."""
    r, g, b = rgb
    return min(PALETTE, key=lambda i: (PALETTE[i][0] - r) ** 2 +
                                      (PALETTE[i][1] - g) ** 2 +
                                      (PALETTE[i][2] - b) ** 2)

def read_png(path):
    try:
        from PIL import Image
    except ImportError:
        sys.exit("Pillow is missing. Install it with:  python -m pip install pillow")
    img = Image.open(path).convert('RGBA')
    w, h = img.size
    rows = []
    for y in range(h):
        row = []
        for x in range(w):
            r, g, b, a = img.getpixel((x, y))
            row.append(0 if a < 128 else closest_index((r, g, b)))
        rows.append(row)
    return rows

def read_txt(path):
    cmap = {'.': 0}
    text_rows = []
    # utf-8-sig: ignores the invisible BOM some editors add at the start
    with open(path, encoding='utf-8-sig') as f:
        for raw in f:
            line = raw.rstrip('\r\n').rstrip()
            if not line or line.startswith('#'):
                continue
            if line.startswith('map '):
                _, ch, idx = line.split()
                cmap[ch] = int(idx)
                continue
            text_rows.append(line)
    if not text_rows:
        sys.exit("No pixel rows found")
    width = len(text_rows[0])
    for i, r in enumerate(text_rows):
        if len(r) != width:
            sys.exit(f"Row {i + 1} has width {len(r)}, expected {width}")
        for ch in r:
            if ch not in cmap:
                sys.exit(f"Char '{ch}' in row {i + 1} has no 'map' line")
    return [[cmap[ch] for ch in r] for r in text_rows]

def to_asm(rows, label):
    out = [f"; {label}: {len(rows[0])}x{len(rows)} px, generated by sprite2db.py",
           f"{label}_W EQU {len(rows[0])}",
           f"{label}_H EQU {len(rows)}"]
    for i, r in enumerate(rows):
        vals = ",".join(f"{v:2d}" for v in r)
        prefix = f"{label} db " if i == 0 else " " * (len(label) + 1) + "db "
        out.append(prefix + vals)
    return "\r\n".join(out) + "\r\n"

if __name__ == "__main__":
    if len(sys.argv) != 4:
        sys.exit("Usage: python sprite2db.py <sprite.png|sprite.txt> <label> <output.inc>")
    src, label, dst = sys.argv[1:]
    rows = read_png(src) if src.lower().endswith('.png') else read_txt(src)
    # Plain ASCII with DOS line endings: what TASM expects
    with open(dst, 'w', encoding='ascii', newline='') as f:
        f.write(to_asm(rows, label))
    print(f"OK: {dst} written ({len(rows[0])}x{len(rows)})")
