;==============================================================================
; EIF205 - Proyecto II - Mastermind (16-bit x86, mode 13h)
; File   : main.asm
; Phase  : 1 - Skeleton (video mode, generic sprite routine, clean exit)
;          1b - First theme sprite (frasco2) replaces the test sprite
;
; Goal of this phase:
;   - Save the original video mode and restore it on exit (RF-14)
;   - Enter mode 13h with INT 10h/00h and write straight to A000h (RG-01)
;   - One generic DibujarSprite routine with transparent color 0 (RG-02/03)
;   - At least one macro used more than once (RT-04)
;==============================================================================

.MODEL SMALL
.STACK 200h

;------------------------------------------------------------------------------
; Constants
;------------------------------------------------------------------------------
TRANSPARENT     EQU 0           ; sprite color index that is never written
VIDEO_SEG       EQU 0A000h      ; mode 13h framebuffer segment
SCREEN_W        EQU 320
SCREEN_WORDS    EQU 32000       ; 64000 bytes / 2, for REP STOSW

;------------------------------------------------------------------------------
; MACRO DRAW_SPRITE
; Pushes the 5 parameters DibujarSprite expects and calls it.
; AX is saved and restored around the call so the caller loses nothing.
; Push order matters: it defines the [bp+n] offsets inside the PROC.
;------------------------------------------------------------------------------
DRAW_SPRITE MACRO px, py, pw, ph, pdata
    push ax
    mov  ax, px
    push ax
    mov  ax, py
    push ax
    mov  ax, pw
    push ax
    mov  ax, ph
    push ax
    mov  ax, OFFSET pdata
    push ax
    call DibujarSprite          ; callee removes the 5 params (RET 10)
    pop  ax
ENDM

;------------------------------------------------------------------------------
; MACRO WAIT_KEY - block until any key is pressed, discard it
;------------------------------------------------------------------------------
WAIT_KEY MACRO
    push ax
    mov  ah, 00h
    int  16h                    ; BIOS keyboard: wait and read key
    pop  ax
ENDM

.DATA
oldVideoMode    db ?            ; mode active before we switched to 13h
targetSeg       dw VIDEO_SEG    ; where drawing goes; later this will point
                                ; to the 64000-byte back buffer (RG-08)

INCLUDE frasco1.inc             ; round potion, generated by sprite2db.py
INCLUDE frasco2.inc             ; tall thin potion, generated by sprite2db.py
INCLUDE frasco3.inc             ; triangular potion, generated by sprite2db.py
INCLUDE frasco4.inc             ; heart potion, generated by sprite2db.py
INCLUDE frasco5.inc             ; square potion, generated by sprite2db.py
INCLUDE frasco6.inc             ; skull potion, generated by sprite2db.py
INCLUDE frasco7.inc             ; star potion, generated by sprite2db.py
INCLUDE frasco8.inc             ; hourglass potion, generated by sprite2db.py
INCLUDE chispa.inc              ; exact-hit icon, generated by sprite2db.py
INCLUDE burbuja.inc             ; partial-hit icon, generated by sprite2db.py
INCLUDE marco1.inc              ; selection frame, frame 1
INCLUDE marco2.inc              ; selection frame, frame 2
INCLUDE caldero1.inc            ; mascot, frame 1
INCLUDE caldero2.inc            ; mascot, frame 2

.CODE
;==============================================================================
; main - program entry point
;==============================================================================
main PROC
    mov  ax, @data
    mov  ds, ax                 ; DS must reach our variables and sprite tables

    call SaveVideoMode
    call SetMode13h

    mov  al, 1                  ; background: default palette blue
    call ClearScreen

    ; Same routine, three positions. The second one overlaps the first
    ; on purpose: if transparency works, no rectangle shows around it.

    DRAW_SPRITE  20, 150, frasco1_W, frasco1_H, frasco1
    DRAW_SPRITE  50, 150, frasco2_W, frasco2_H, frasco2
    DRAW_SPRITE  80, 150, frasco3_W, frasco3_H, frasco3
    DRAW_SPRITE 110, 150, frasco4_W, frasco4_H, frasco4
    DRAW_SPRITE 140, 150, frasco5_W, frasco5_H, frasco5
    DRAW_SPRITE 170, 150, frasco6_W, frasco6_H, frasco6
    DRAW_SPRITE 200, 150, frasco7_W, frasco7_H, frasco7
    DRAW_SPRITE 230, 150, frasco8_W, frasco8_H, frasco8
    DRAW_SPRITE 20, 175, chispa_W, chispa_H, chispa
    DRAW_SPRITE 40, 175, burbuja_W, burbuja_H, burbuja
    DRAW_SPRITE 19, 149, marco1_W, marco1_H, marco1
    DRAW_SPRITE 140, 60, caldero1_W, caldero1_H, caldero1
    DRAW_SPRITE 170, 60, caldero2_W, caldero2_H, caldero2

    WAIT_KEY

    call RestoreVideoMode
    call ExitToDos
main ENDP

;------------------------------------------------------------------------------
; SaveVideoMode
; Receives : nothing
; Returns  : oldVideoMode = current BIOS video mode
; Destroys : nothing
;------------------------------------------------------------------------------
SaveVideoMode PROC
    push ax
    push bx                     ; INT 10h/0Fh returns active page in BH
    mov  ah, 0Fh
    int  10h                    ; AL = current mode
    mov  oldVideoMode, al
    pop  bx
    pop  ax
    ret
SaveVideoMode ENDP

;------------------------------------------------------------------------------
; SetMode13h - switch to 320x200, 256 colors
; Receives : nothing
; Returns  : nothing
; Destroys : nothing
;------------------------------------------------------------------------------
SetMode13h PROC
    push ax
    mov  ax, 0013h              ; AH=00h set mode, AL=13h
    int  10h
    pop  ax
    ret
SetMode13h ENDP

;------------------------------------------------------------------------------
; RestoreVideoMode - put back whatever mode DOS had before the game
; Receives : oldVideoMode
; Returns  : nothing
; Destroys : nothing
;------------------------------------------------------------------------------
RestoreVideoMode PROC
    push ax
    mov  ah, 00h
    mov  al, oldVideoMode
    int  10h
    pop  ax
    ret
RestoreVideoMode ENDP

;------------------------------------------------------------------------------
; ClearScreen - fill the whole target surface with one color
; Receives : AL = palette index
; Returns  : nothing
; Destroys : nothing
;------------------------------------------------------------------------------
ClearScreen PROC
    push ax
    push cx
    push di
    push es
    mov  es, targetSeg          ; ES -> surface we are drawing on
    xor  di, di                 ; start at pixel (0,0)
    mov  ah, al                 ; same color in both bytes: 2 pixels per STOSW
    mov  cx, SCREEN_WORDS
    cld                         ; DI must move forward
    rep  stosw
    pop  es
    pop  di
    pop  cx
    pop  ax
    ret
ClearScreen ENDP

;------------------------------------------------------------------------------
; DibujarSprite - generic sprite blitter with transparency
; Receives (stack, pushed in this order):
;     X, Y, WIDTH, HEIGHT, SPRITE_PTR (offset in DS)
;   Frame after PUSH BP:
;     [bp+12]=X  [bp+10]=Y  [bp+8]=WIDTH  [bp+6]=HEIGHT  [bp+4]=SPRITE_PTR
; Returns  : nothing
; Destroys : nothing (removes its own 10 bytes of params with RET 10)
; Notes    : sprite bytes equal to TRANSPARENT are skipped, so the
;            background shows through. No clipping: caller keeps the
;            sprite inside the screen.
;------------------------------------------------------------------------------
DibujarSprite PROC
    push bp
    mov  bp, sp
    push ax
    push bx
    push cx
    push dx
    push si
    push di
    push es

    mov  es, targetSeg          ; ES -> surface we are drawing on

    ; DI = Y*320 + X  (top-left pixel of the sprite)
    mov  ax, [bp+10]
    mov  bx, SCREEN_W
    mul  bx                     ; DX:AX = Y*320; DX is 0 because Y < 200
    add  ax, [bp+12]
    mov  di, ax

    mov  si, [bp+4]             ; SI walks the sprite table byte by byte
    mov  dx, [bp+6]             ; DX = rows still to draw
    cld                         ; LODSB must advance SI

DS_Row:
    mov  cx, [bp+8]             ; CX = pixels left in this row
DS_Col:
    lodsb                       ; AL = sprite pixel, SI moves to the next one
    cmp  al, TRANSPARENT
    je   DS_Skip                ; transparent: leave the background as is
    mov  es:[di], al
DS_Skip:
    inc  di
    loop DS_Col

    ; We are WIDTH pixels to the right of the row start; jump to the
    ; same X one line down.
    add  di, SCREEN_W
    sub  di, [bp+8]
    dec  dx
    jnz  DS_Row

    pop  es
    pop  di
    pop  si
    pop  dx
    pop  cx
    pop  bx
    pop  ax
    pop  bp
    ret  10                     ; discard the 5 word parameters
DibujarSprite ENDP

;------------------------------------------------------------------------------
; ExitToDos - terminate the program with return code 0
; Receives : nothing
; Returns  : does not return
;------------------------------------------------------------------------------
ExitToDos PROC
    mov  ax, 4C00h
    int  21h
ExitToDos ENDP

END main
 